export const SystemPermissions = {
    ViewAllUser: 'View all User',
    GetRoleForUser: 'Get Role ForUser',
    AssignRoleToUser: 'Assign Role ToUser',
    RoleView: 'View Role',
    RoleViewById: 'Get Role By Id',
    RoleCreate: 'Create new Role',
    RoleEdit: 'Edit Role',
    RoleDelete: 'Delete Role',
    AssignPermissionToRole: 'Assign Permission To Role',
    GetPermissionForRole: 'Get Permissions For Role',
    EmployeeView: 'View Employee',
    EmployeeCreate: 'Create new Employee',
    EmployeeEdit: 'Edit Employee',
    EmployeeDelete: 'Delete Employee',
    MemberUnitView: 'View Member Unit',
    MemberUnitCreate: 'Create new Member Unit',
    MemberUnitEdit: 'Edit Member Unit',
    MemberUnitDelete: 'Delete Member Unit' 
};